spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: rui
    password: Qa4qtWT7
    url: jdbc:postgresql://47.100.38.198:5433/dbc63c43bde7064ae7a98b422068ecd026ceshi_db
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache
      poolPreparedStatements: true
      # SQL合并配置
      filters: mergeStat,wall
      #指定每个连接上PSCache的大小
      maxPoolPreparedStatementPerConnectionSize: 20
      #合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: true
      #慢SQL记录
      filter:
        stat:
          log-slow-sql: true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: rui
        login-password: 04e42c57bcb24c5a81c9fe9cff33760d
        reset-enable: true
